development:
  host: localhost
  database: whoot_development

test:
  host: localhost
  database: whoot_test

staging:
  host: dbh55.mongolab.com
  port: 27557
  username: staging_pluto
  password: nIwo8Dnqie30xW
  database: whoot_staging

# set these environment variables on your prod server
production:
  host: localhost
  database: whoot_production
#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
