defaults: &defaults

development:
  host: localhost
  database: whoot_development
  raise_not_found_error: false
  autocreate_indexes: true

#development:
#  host: dbh79.mongolab.com
#  port: 27797
#  username: production_mars
#  password: PuU3Qb4HGt5s
#  database: heroku_app1680692
#  raise_not_found_error: false

test:
  host: localhost
  database: whoot_test
  raise_not_found_error: false
  autocreate_indexes: true

staging:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  raise_not_found_error: false

production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  raise_not_found_error: false
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
