#send_scout_data:
#  #cron: "0 0 * * *"
#  every: 1m
#  class: SendScoutData
#  args:
#  description: "This job calls the scout executable to send log data to scout."

#recalculate_venue_pop:
#  every: 10m
#  class: RecalculateVenuePopularity
#  #args: 'hour'
#  description: "This job recalculates venue popularities"
#
#recalculate_tag_pop:
#  every: 10m
#  class: RecalculateTagPopularity
#  #args: 'hour'
#  description: "This job recalculates tag popularities"

#send_daily_reminder:
#  cron: 0 16 * * * America/New_York
#  class: SendDailyReminder
#  description: "Sends a daily reminder via push notification or email"

set_day_analytics:
  cron: 30 4 * * * America/New_York
  class: SetDayAnalytics
  description: "Updates the DayAverages collection once a day"