ruby:
  version: 1.9
  compile_mode: jit
  debug: false
  interactive: true #debugger
  profile_api: false

web:
  rackup: config.ru
  host: localhost
  static: public
  session-timeout: 30m

environment:
  RAILS_ENV: development
  RACK_ENV: development