require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InvitePostsController do

  # This should return the minimal set of attributes required to create a valid
  # Invitepost. As you add validations to Invitepost, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all inviteposts as @inviteposts" do
      invitepost = Invitepost.create! valid_attributes
      get :index
      assigns(:invite_posts).should eq([invitepost])
    end
  end

  describe "GET show" do
    it "assigns the requested invitepost as @invitepost" do
      invitepost = Invitepost.create! valid_attributes
      get :show, :id => invitepost.id.to_s
      assigns(:invitepost).should eq(invitepost)
    end
  end

  describe "GET new" do
    it "assigns a new invitepost as @invitepost" do
      get :new
      assigns(:invitepost).should be_a_new(Invitepost)
    end
  end

  describe "GET edit" do
    it "assigns the requested invitepost as @invitepost" do
      invitepost = Invitepost.create! valid_attributes
      get :edit, :id => invitepost.id.to_s
      assigns(:invitepost).should eq(invitepost)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Invitepost" do
        expect {
          post :create, :invitepost => valid_attributes
        }.to change(Invitepost, :count).by(1)
      end

      it "assigns a newly created invitepost as @invitepost" do
        post :create, :invitepost => valid_attributes
        assigns(:invitepost).should be_a(Invitepost)
        assigns(:invitepost).should be_persisted
      end

      it "redirects to the created invitepost" do
        post :create, :invitepost => valid_attributes
        response.should redirect_to(Invitepost.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved invitepost as @invitepost" do
        # Trigger the behavior that occurs when invalid params are submitted
        Invitepost.any_instance.stub(:save).and_return(false)
        post :create, :invitepost => {}
        assigns(:invitepost).should be_a_new(Invitepost)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Invitepost.any_instance.stub(:save).and_return(false)
        post :create, :invitepost => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested invitepost" do
        invitepost = Invitepost.create! valid_attributes
        # Assuming there are no other inviteposts in the database, this
        # specifies that the Invitepost created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Invitepost.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => invitepost.id, :invitepost => {'these' => 'params'}
      end

      it "assigns the requested invitepost as @invitepost" do
        invitepost = Invitepost.create! valid_attributes
        put :update, :id => invitepost.id, :invitepost => valid_attributes
        assigns(:invitepost).should eq(invitepost)
      end

      it "redirects to the invitepost" do
        invitepost = Invitepost.create! valid_attributes
        put :update, :id => invitepost.id, :invitepost => valid_attributes
        response.should redirect_to(invitepost)
      end
    end

    describe "with invalid params" do
      it "assigns the invitepost as @invitepost" do
        invitepost = Invitepost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Invitepost.any_instance.stub(:save).and_return(false)
        put :update, :id => invitepost.id.to_s, :invitepost => {}
        assigns(:invitepost).should eq(invitepost)
      end

      it "re-renders the 'edit' template" do
        invitepost = Invitepost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Invitepost.any_instance.stub(:save).and_return(false)
        put :update, :id => invitepost.id.to_s, :invitepost => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested invitepost" do
      invitepost = Invitepost.create! valid_attributes
      expect {
        delete :destroy, :id => invitepost.id.to_s
      }.to change(Invitepost, :count).by(-1)
    end

    it "redirects to the inviteposts list" do
      invitepost = Invitepost.create! valid_attributes
      delete :destroy, :id => invitepost.id.to_s
      response.should redirect_to(inviteposts_url)
    end
  end

end
